sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-009
env:
  global:
    -
      # LTD_AWS_ID
      secure: an6RkJPMMZRt4NJI8UETgXp4nVvDFVuHX17bNe67bvtnhA2stBwNdxJueZjyj03cAkFTqAqfx+/KO3EwJilD4kG2exDfOy32VU8hMsXxXppFxih10BF7QefYDyChfG7WY4X+m2+pvGn0G+Jdn/SZoIaIhiVVbo03QEG6Cytwdg1etlPoFaSmzsnzExHGSMdUu4YNv/OrN0j0o99RRIT/WJTpgX0Kq3MIbTF7ZtxCO+UB/M3l3bfG/Gw+xu81mpNVtDVp2C1eAV9ESDJG9aq2pTdX+ctrc3ZVQhwrDJTDVah3yrWX2FXf8usDNUvNzS7wwg3kdTd3YkYhcth146RlZO3jLz6nm9RA0BVR+Vl88YSV+uhmTBOiKAxNfg0N2MVbNqzWR+901QV/3zuad5fkDC5COR0ewDnk9Wf71zyoYDRbpFiMcgjMoMO4xxwS62X38W2TnZf7LoLTMUMjxOgpjusiEdB4zCXI2SFvcb+Sh7Ets8UpOfnEO1cHpDth9/5iW/vE0wmfajIS+ddxuT2u637QcaG8ZVetFPeXDYrK9HWvtVwLUIIMw7bmiEHhm1Al8PrxmJLTflDLv4XfEnfmn3pE69udJVw1mhVKCKny+XOxY80JWijF05p9+LJOZ98/Bz3bd4LeOBW0tHKfgTDmJtD4rbqcXb5oAHL/aB4EOws=
    -
      # LTD_AWS_SECRET
      secure: dkn5JN5nJd8P+K2xwx5E2qdHsu7lw0RUDT5fM+rhaMccXD4pfDwcZGyyr24xAvUSUWrFBW+o7IRXEzINvtZpSIlCfNcfOViX/aHF+bEC8TtHwFhKOMgDByuk+0liWo5DYuFpA1ec2WXf0bGE04JUK7naMlAHIUZImoNW13MpZEMyDJDT0+uXg6jy+aXu/eAYnYo4mpVaXi7wSIhJcOYqa88byhuDgCo70iqHkb2ROv5rqH1hcm7twCyJnlpSPBjLhQjwbox04GpLkVJhIIfeXgqUF5U8wZlKjwSYDiI2FHO/zX7ZOTz+qV1uR5ZyNfyLJVXH6ZaAH258pjO3ZTTPpDJ/rs+Vd3SO+P5Hvn7xXIcD7FjRe2IGA6dg5IxqPGZVXJJewbC3tyGUtbvrB2PlwCAdPVg0rEoyAy2/H/T5/kNSjUm6bIhDwsgEYRy9GvH3BZyym2A4dQP+7FZWzV4mP+8Nvcwvjj96qh2MPTtHFR5kVdIMLTsI5XH1p26afAg0QeasYIxyuPQlCZxKTU4WGh2ILhDvvmM4IURIWXZJUm3PhW5IOzaqnqdZE/RIAlEIf3caL1laiJUCA9Ek2BIpSE8eTrrCJSGtRDlcZvic7VU1K3RHnDdBIkcsWv0Uv49VKDM4UwFdjBJbbqFaOxTV8s5hFKLf8X0ILitsdbk9ag8=
    -
      # LTD_USERNAME
      secure: TXXC08CRiOk8gj2razrdg8UvHorb7d49KlF0i30r+EriRsddRlL+W5yRTUKMETAswgkftgOtxpFiRy+69Bm7P9On3J6viUTLCh36ceoayOzb+EXrG7hkZVzagZqnnJHfFbFTySUQg20XI4VaPBkQVcFSCfwQEuB/+96ofh2o+UPyAxRPQRCJBxopQUmVpWIoxhCtCBBlGRcHYGGl/dbNhHsZRv1Ydvkx52sTZmYZz8210U2SrPIdeQLkos0gG8n+WMFYOIhkRSHgtwq/1JSSSMGRuVHJtR+KUjAHtBikTKvZp7AOeEwbVE9SDouOFTZLSHYNdwCvByGV989i9X2AoY2DXzBLsmuvFzfBxGz5DkbWEqXf5yHe0o18g1cVhuJKZRc3OJVY3J3OlDjB/cqMoKbE4f2yw5vWwfBll7DWWR2kvNIVekqsQbOFxpBVupI8JJ+NwZ51fUd58YHYAqJdTQm+//ZHf2IzLsBVNI4Zhs2Rj2MHYUzYHCDyaw/Gc0XrXja2tG543q1ZO+A6Lyd+ox7ZVDFMv+/yNLymIy6g7FngyQ8fmWsM5UpCBJS0+4+9SwBd5Iw8SuMdG/QQzjZUC9LclH2HumZDecZF7QGekXOnWAvCA2jG8g0Jpg5tmVGv+p83I0HvB0JQ+UGaK/mXz5QblCVZcTPs3+JLZtBLNso=
    -
      # LTD_PASSWORD
      secure: ahE9rgf+Cx087aHvqylqTBwl2SeuUmDnZu2Dj0d+Ki5isrTVxoJGe4kSLFNJvrIp8DHEN29Wp5Pzx+Lc2n0O6rgPEDpOCjN1XgWMy1r+cBThrNeuzKn/czTrdbk8DVXgHrZFOPNqXYFPhq6qUf+US2u67CQJlPJ7YNq3vCVAVrIlkovHtOz38DB55HZZQmYiuVYbV2LBmHzTfz7NYDpnKC1N0i5TOVLB2HCcQrBlarYoB9H7z5Ig3e/EgKiQA9oW0TdZQmfzFLYMfh0VaWLHZoOxrza+vNHJXW8l8eM+NKFwKXAZQI59mzI2lN6Z9W9btwrxNgEnUlQLd+7isPEFGFeR1nYdTT2C9TxEbTqGksm0cMo1Ypb3qS0IEWB356Ou2LtMrQZtdk84fJbv9+uJEzoY3ehHbAiHgUehR8SdgzxUp43hQ1oG6bR7QMOB+WDszv/ivSbt1dcaEVNicE6LITcqquSWU6qsYDjWw9eemluEOsn8K78bWuhKwPXAECRJVsYlyAz6nUs0Yg7gfo20ABfhNKqV3kL7P1ecq9LEN0C4FvLiPEJ05EVp1Vxz/pvhTKcR2fyX5dXX7bn5znghwDsDxknN1dt13mdxtbclYp82W5LUQQ3MJiwLT63TatRGKzqbFMnps+fE/rLeZ0bDpfa93ALXgAooPHR4DuoQ0/M=
